CREATE TABLE [ut].[EXTENSION] (
    [ID]    INT            NOT NULL,
    [VALUE] NVARCHAR (MAX) NOT NULL,
    [KEY]   NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_EXTENSION] PRIMARY KEY CLUSTERED ([ID] ASC)
);