if OBJECT_ID('[ut].[TEST_PLAN_ALLOCATION]','U') IS NOT NULL
    drop table [ut].[TEST_PLAN_ALLOCATION]
GO

CREATE TABLE [ut].[TEST_PLAN_ALLOCATION] (
    [TEST_ID]             INT           NOT NULL,
    [TEST_PLAN_ID]        INT           NOT NULL,
    [CONNECTION_KEY]      VARCHAR(1000) NULL,
    [EXECUTION_METHOD_ID] INT           NULL,
    CONSTRAINT [PK_TEST_PLAN_ALLOCATION] PRIMARY KEY CLUSTERED ([TEST_ID] ASC, [TEST_PLAN_ID] ASC),
    CONSTRAINT [FK_ALLOCATION_TEST_ID] FOREIGN KEY ([TEST_ID]) REFERENCES [ut].[TEST] ([ID]),
    CONSTRAINT [FK_ALLOCATION_TEST_PLAN_ID] FOREIGN KEY ([TEST_PLAN_ID]) REFERENCES [ut].[TEST_PLAN] ([ID])
);
