CREATE TABLE [ut].[TEST_PLAN_EXTENSION](
    [TEST_PLAN_ID]    INT                   NOT NULL,
    [EXTENSION_ID]    INT                   NOT NULL,
    [ACTIVE_INDICATOR]    CHAR (1)
     CONSTRAINT [DF_UT_TEST_PLAN_EXTENSION_ACTIVE_INDICATOR]
      DEFAULT ('Y')                         NOT NULL,
    CONSTRAINT [PK_TEST_PLAN_EXTENSION] PRIMARY KEY CLUSTERED ([TEST_PLAN_ID],[EXTENSION_ID] ASC)
);