CREATE TABLE [ut].[TEST_EXTENSION] (
    [TEST_ID]    INT            NOT NULL,
    [EXTENSION_ID]    INT       NOT NULL,
    [ACTIVE_INDICATOR]    CHAR (1)
     CONSTRAINT [DF_UT_TEST_EXTENSION_ACTIVE_INDICATOR]
      DEFAULT ('Y')                          NOT NULL,
    CONSTRAINT [PK_TEST_EXTENSION] PRIMARY KEY CLUSTERED ([TEST_ID],[EXTENSION_ID] ASC)
);